services:
  portfolio-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://<FREESQLDB_HOST>:3306/<FREESQLDB_DBNAME>?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=<FREESQLDB_USER>
      - SPRING_DATASOURCE_PASSWORD=<FREESQLDB_PASSWORD>
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

#  mysql:
#    image: mysql:8.0
#    environment:
#      MYSQL_ROOT_PASSWORD: root_password
#      MYSQL_DATABASE: portfolio
#      MYSQL_USER: portfolio_user
#      MYSQL_PASSWORD: portfolio_password
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql
#      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql
#    restart: unless-stopped
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#      start_period: 30s

#volumes:
#  mysql_data: 