services:
  - type: web
    name: portfolio-app
    env: docker
    plan: starter
    region: oregon
    buildCommand: docker build -t portfolio-app .
    startCommand: docker run -p $PORT:9000 portfolio-app
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: docker
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: portfolio-db
          property: username
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: portfolio-db
          property: password
      - key: PORT
        value: 9000
    healthCheckPath: /actuator/health
    autoDeploy: true

databases:
  - name: portfolio-db
    databaseName: portfolio
    user: portfolio_user
    plan: starter
    region: oregon 