services:
  - type: web
    name: portfolio-backend
    runtime: java
    preBuildCommand: chmod +x build.sh
    buildCommand: ./build.sh
    startCommand: java -jar target/Portfolio-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
    healthCheckPath: /api/health 